name: example

dependencies:
  class_extensions_annotations: ^0.1.0
  to_string_extension_annotations: ^0.1.0

dev_dependencies:
  build_runner: ^1.0.0
  class_extensions: ^0.3.0
  to_string_extension: ^0.1.0
