builders:
  dummy_extension_generators:
    import: "package:to_string_extension/to_string_extension.dart"
    builder_factories: ["toStringDummyBuilder"]
    build_extensions: {".dart": []}
    auto_apply: dependents
