name: to_string_extension
version: 0.1.1
author: svarzee <svarzee@gmail.com>
homepage: https://github.com/svarzee/to_string_extension
description: >-
  Uses class_extensions to generate toString for nicely looking text representation of data objects.
environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  class_extensions: ^0.3.0
  to_string_extension_annotations: ^0.1.0
  analyzer: '>=0.37.1 <0.39.0'
  build: '>=0.12.6 <2.0.0'
  source_gen: ^0.9.0

dev_dependencies:
  build_runner: ^1.0.0

